format: "[&6%prefix&r] &3%name&7:&r %message"
users:
  mete0:
    groups:
    - dev
    - root
    - libsdisguises
    - lobby
    permissions:
      essentials.silentjoin.vanish: true
      essentials.speed.bypass: true
      essentials.eco: true
      essentials.exp.set: true
      essentials.exp.set.others: true
      essentials.exp.give: true
      essentials.exp.give.others: true
  Nyastor_:
    groups:
    - root
    - libsdisguises
    - lobby
  DsaaaaaaaASDD:
    groups:
    - root
    - libsdisguises
  narciss:
    groups:
    - admin
    - worldedit
    - commandblock
  Minner:
    groups:
    - admin
    - worldedit
  Spam_Dex:
    groups:
    - helper
    - creative
  Silvano:
    groups:
    - helper
  Silird:
    groups:
    - dev
    - root
    - libsdisguises
  LittleFox:
    groups:
    - helper
    - creative
  tur1k_:
    groups:
    - root
    - libsdisguises
    - lobby
  Mephisto_Tersis:
    groups:
    - admin
    - worldedit
  proninyaroslav:
    groups:
    - helper
  Faust_Morrowizn:
    groups:
    - moder
    - worldedit
  RUSSELL:
    groups:
    - helper
  Maironaur:
    groups:
    - builder
    - lobby
  WooW:
    groups:
    - helper
    - creative
  Zemanter:
    groups:
    - helper
  red:
    groups:
    - helper
  1523132:
    groups:
    - helper
  KnyzZ:
    groups:
    - helper
  sallad1n:
    groups:
    - pedo
    - default
groups:
# Группа по-умолчанию
  default:
    prefix: "Игрок"
    permissions:
      worldprotect.region.world: true
      worldprotect.region.world_nether: true
      worldprotect.region.world_the_end: false
      worldprotect.flag.pvp: true
      worldprotect.flag.piston: true
      worldprotect.flag.vehicleNaturalDestroy: true
      minecraft.command.me: false
      worldedit.selection.pos: true
      worldedit.selection.hpos: true
      worldedit.wand: true
      worldedit.wand.toggle: true
      worldedit.selection.expand: true
      worldedit.help: true
      essentials.exp: true
      essentials.keepxp: true
      essentials.chat.shout: true
      essentials.warp: true
      essentials.warp.list: true
      essentials.signs.create.protection: true
      essentials.signs.custom.use: true
      essentials.signs.break.protection: true
      essentials.signs.use.balance: true
      essentials.signs.use.buy: true
      essentials.signs.use.warp: true
      essentials.silentquit: true
      essentials.silentjoin: true
      essentials.sethome.multiple: true
      essentials.msg: true
      essentials.balance: true
      essentials.mail: false
      essentials.help: true
      essentials.home: true
      essentials.home.bed: true
      essentials.sethome: true
      essentials.delhome: true
      essentials.tpa: true
      essentials.tpaccept: true
      essentials.tpahere: true
      essentials.tpdeny: true
      essentials.rules: true
      essentials.list: true
      essentials.kit: true
      essentials.kits.start: true
      essentials.time: true
      essentials.ignore: true
    worlds:
      lobby:
        worldedit.wand: false
#
  helper:
    prefix: "&2Помощник"
    permissions:
      worldprotect.unlimited: true
      essentials.exp.others: true
      essentials.sleepingignored: true
      essentials.kits.build: true
      essentials.kits.vip_daily: true
      essentials.chat.color: true
      essentials.tp: true
      essentials.tp.position: true
      essentials.chat.ignoreexempt: true
      essentials.clearinventory: true
      essentials.fly: true
      essentials.fly.safelogin: true
      essentials.god: true
      essentials.back: true
      essentials.back.ondeath: true
      essentials.hat: true
      bessentials.kick.set: true
      bessentials.kick.notify: true
      bessentials.mute.set: true
      bessentials.mute.notify: true
      bessentials.ban.notify: true
      bessentials.mute.pardon: true
      spawn.other: true
    inheritance:
    - default
#
  moder:
    prefix: "&1Модератор"
    permissions:
      worldprotect.admin: true
      worldprotect.region.world_the_end: true
      essentials.sethome.multiple.unlimited: true
      essentials.gc: true
      essentials.hat: true
      essentials.gamemode: true
      essentials.kill: true
      essentials.home.others: true
      essentials.tp.others: true
      essentials.tpaall: true
      essentials.tphere: true
      essentials.warp.otherplayers: true
      essentials.world: true
      essentials.top: true
      essentials.firework: true
      essentials.feed: true
      essentials.feed.others: true
      essentials.heal: true
      essentials.heal.others: true
      essentials.me: true
      essentials.motd: true
      essentials.kit.others: true
      essentials.getpos.others: true
      essentials.ptime: true
      essentials.ptime.others: true
      essentials.enderchest: true
      essentials.enderchest.others: true
      essentials.invsee: true
      essentials.vanish: true
      essentials.vanish.effect: true
      essentials.near: true
      essentials.ext: true
      essentials.item: true
      essentials.speed: true
      bessentials.ban.ip: true
      essentials.give: true
      bessentials.ban.set: true
      bessentials.ban.pardon: true
    inheritance:
    - helper
    worlds:
      lobby:
        worldprotect.admin: false
#
  admin:
    prefix: "&4Админ"
    permissions:
      worldprotect.flag.build: true
      worldprotect.flag.use: true
      worldprotect.flag.damage: true
      worldprotect.flag.teleport: true
      worldprotect.flag.creatureSpawn: true
      worldprotect.flag.entityBlockExplode: true
      worldprotect.flag.command: true
      worldprotect.flag.grow: true
      worldprotect.flag.burn: true
      worldprotect.flag.spread: true
      worldprotect.flag.pva: true
      worldprotect.flag.pve: true
      worldprotect.flag.bukkitEmptyWater: true
      worldprotect.flag.portalCreation: true
      worldprotect.flag.hungry: true
      worldprotect.flag.bukkitEmptyLava: true
      nocheatplus.bypass: true
      bessentials.ban.unlimited: true
      bessentials.mute.unlimited: true
      essentials.nick: true
      essentials.nick.color: true
      essentials.nick.format: true
      essentials.nick.magic: true
      essentials.heal.cooldown.bypass: true
      essentials.list.hidden: true
      essentials.realname: true
      essentials.enderchest.modify: true
      essentials.invsee.modify: true
      essentials.signs.protection.override: true
      essentials.vanish.see: true
      essentials.vanish.interact: true
      essentials.vanish.others: true
      essentials.vanish.effect: false
      mongoauth.account.create: true
      bessentials.ban.immunity: true
      bessentials.mute.immunity: true
      bessentials.kick.immunity: true
      attack.pass_fly_attack: true
      attack.pass_god_attack: true
      essentials.kits.vip_daily: true
      essentials.kits.vip_monthly: true
      essentials.signs.color: true
      essentials.speed.fly: true
      essentials.chat.url: true
      essentials.broadcast: true
      essentials.fly.others: true
      essentials.god.others: true
      essentials.kill.exempt: true
      essentials.sethome.others: true
      essentials.delhome.others: true
      essentials.setwarp: true
      essentials.delwarp: true
      essentials.warp.overwrite.*: true
      essentials.enchant: true
      essentials.firework.fire: true
      essentials.mail.sendall: true
      essentials.msg.color: true
      essentials.msg.magic: true
      essentials.msg.format: true
      essentials.msg.url: true
      essentials.kit.exemptdelay: true
      essentials.time.set: true
      essentials.tptoggle: true
      essentials.antioch: true
      essentials.lightning: true
      essentials.lightning.others: true
      essentials.burn: true
      essentials.killall: true
      essentials.remove: true
      essentials.spawner: true
      essentials.spawner.*: true
      essentials.nick.others: true
      essentials.clearinventory.others: true
      essentials.socialspy: true
      essentials.spawnmob: true
      essentials.spawnmob.*: true
      essentials.spawnmob.stack: true
      essentials.thunder: true
      essentials.itemspawn.exempt: true
      essentials.itemspawn.item-all: true
      essentials.oversizedstacks: true
      essentials.itemspawn.meta-title: true
      essentials.itemspawn.meta-author: true
      essentials.itemspawn.meta-lore: true
      essentials.itemspawn.meta-book: true
      essentials.itemspawn.meta-head: true
      essentials.itemspawn.meta-firework: true
      essentials.itemspawn.meta-name: true
      essentials.more: true
      essentials.repair: true
      essentials.repair.armor: true
      essentials.repair.enchanted: true
      essentials.repair.all: true
      essentials.speed.others: true
      essentials.speed.walk: true
      essentials.unlimited: true
      essentials.enchantments.*: true
    inheritance:
    - moder
# 
  root:
    prefix: "&4root"
    permissions:
      spigot.commandblock: true
      minecraft.command.gamerule: true
      worldedit.limit: true
      worldedit.global-mask: true
      worldedit.scripting.execute: true
      spawn.set: true
      essentials.joinfullserver: true
      essentials.essentials: true
      essentials.butcher: true
      essentials.god.pvp: true
      essentials.invsee.preventmodify: true
      essentials.socialspy.others: true
      essentials.signs.create.custom: true
      essentials.signs.create.balance: true
      essentials.signs.create.buy: true
      essentials.signs.create.disposal: true
      essentials.signs.create.enchant: true
      essentials.signs.create.free: true
      essentials.signs.create.gamemode: true
      essentials.signs.create.heal: true
      essentials.signs.create.info: true
      essentials.signs.create.kit: true
      essentials.signs.create.mail: true
      essentials.signs.create.repair: true
      essentials.signs.create.sell: true
      essentials.signs.create.time: true
      essentials.signs.create.trade: true
      essentials.signs.create.warp: true
      essentials.signs.create.weather: true
      essentials.signs.break.kit: true
      essentials.signs.break.buy: true
      essentials.signs.break.custom: true
      essentials.tptoggle.others: true
      essentials.weather: true
      essentials.gamemode.others: true
    inheritance:
    - admin
    - plugman
    - worldedit
# access to lobby
  lobby:
    worlds:
      lobby:
        worldedit.wand: true
        minecraft.command.gamemode: true
        worldprotect.admin: true
        worldprotect.region.lobby: true
# Группа строитель  
  builder:
    prefix: "Architect"
    inheritance:
    - admin
    - worldedit
# Вспомогательные группы
  plugman:
    permissions:
      plugman.help: true
      plugman.list: true
      plugman.info: true
      plugman.usage: true
      plugman.enable: true
      plugman.enable.all: true
      plugman.disable: true
      plugman.disable.all: true
      plugman.restart: true
      plugman.restart.all: true
      plugman.load: true
      plugman.reload: true
      plugman.unload: true
# Плагин маскировки
  libsdisguises:
    permissions:
      libsdisguises.seecmd.disguise: true
      libsdisguises.seecmd.disguiseentity: true
      libsdisguises.seecmd.disguisehelp: true
      libsdisguises.seecmd.disguiseplayer: true
      libsdisguises.seecmd.disguiseradius: true
      libsdisguises.seecmd.undisguise: true
      libsdisguises.seecmd.undisguiseentity: true
      libsdisguises.seecmd.undisguiseplayer: true
      libsdisguises.seecmd.undisguiseradius: true
      libsdisguises.seecmd.disguiseclone: true
      libsdisguises.disguise.*: true
      libsdisguises.disguise.*.*: true
      libsdisguises.disguiseplayer.*: true
      libsdisguises.disguiseplayer.*.*: true
      libsdisguises.disguiseradius: true
      libsdisguises.undisguise: true
      libsdisguises.undisguiseentity: true
      libsdisguises.undisguiseplayer: true
      libsdisguises.undisguiseradius: true
#
  worldedit:
    permissions:
      worldedit.biome.list: true
      worldedit.biome.info: true
      worldedit.biome.set: true
      worldedit.brush.sphere: true
      worldedit.brush.cylinder: true
      worldedit.brush.clipboard: true
      worldedit.brush.smooth: true
      worldedit.brush.ex: true
      worldedit.brush.gravity: true
      worldedit.chunk.info: true
      worldedit.chunk.list: true
      worldedit.chunk.delete: true
      worldedit.clipboard.copy: true
      worldedit.clipboard.cut: true
      worldedit.clipboard.paste: true
      worldedit.clipboard.rotate: true
      worldedit.clipboard.flip: true
      worldedit.clipboard.clear: true
      worldedit.fast: true
      worldedit.generation.cylinder: true
      worldedit.generation.sphere: true
      worldedit.generation.pumpkins: true
      worldedit.generation.pyramid: true
      worldedit.generation.shape: true
      worldedit.history.undo: true
      worldedit.history.redo: true
      worldedit.history.clear: true
      worldedit.navigation.unstuck: true
      worldedit.navigation.ascend: true
      worldedit.navigation.descend: true
      worldedit.navigation.ceiling: true
      worldedit.navigation.thru.command: true
      worldedit.navigation.jumpto.command: true
      worldedit.navigation.thru.tool: true
      worldedit.navigation.jumpto.tool: true
      worldedit.navigation.up: true
      worldedit.region.set: true
      worldedit.region.line: true
      worldedit.region.replace: true
      worldedit.region.overlay: true
      worldedit.region.center: true
      worldedit.region.naturalize: true
      worldedit.region.walls: true
      worldedit.region.faces: true
      worldedit.region.smooth: true
      worldedit.region.move: true
      worldedit.region.stack: true
      worldedit.region.flora: true
      worldedit.region.forest: true
      worldedit.regen: true
      worldedit.region.deform: true
      worldedit.region.hollow: true
      worldedit.schematic.list: true
      worldedit.schematic.load: true
      worldedit.schematic.save: true
      worldedit.schematic.formats: true
      worldedit.selection.chunk: true
      worldedit.selection.contract: true
      worldedit.selection.shift: true
      worldedit.selection.outset: true
      worldedit.selection.inset: true
      worldedit.selection.size: true
      worldedit.analysis.count: true
      worldedit.analysis.distr: true
      worldedit.snapshots.list: true
      worldedit.snapshots.restore: true
      worldedit.superpickaxe: true
      worldedit.superpickaxe.area: true
      worldedit.superpickaxe.recursive: true
      worldedit.tool.info: true
      worldedit.tool.tree: true
      worldedit.tool.replacer: true
      worldedit.tool.data-cycler: true
      worldedit.tool.flood-fill: true
      worldedit.tool.deltree: true
      worldedit.tool.farwand: true
      worldedit.tool.lrbuild: true
      worldedit.brush.options.mask: true
      worldedit.brush.options.material: true
      worldedit.brush.options.range: true
      worldedit.brush.options.size: true
      worldedit.fill: true
      worldedit.fill.recursive: true
      worldedit.drain: true
      worldedit.fixlava: true
      worldedit.fixwater: true
      worldedit.removeabove: true
      worldedit.removebelow: true
      worldedit.removenear: true
      worldedit.replacenear: true
      worldedit.snow: true
      worldedit.thaw: true
      worldedit.green: true
      worldedit.extinguish: true
      worldedit.remove: true
#
  creative:
    prefix: "Креатив"
    permissions:
      essentials.gamemode: true
    inheritance:
    - default
#
  commandblock:
    permissions:
      spigot.commandblock: true
  dev:
    prefix: "&e&lDEV"
  pedo:
    prefix: "&dПринцесса"
    permissions:
      essentials.tp: true
      essentials.tp.position: true
      essentials.gamemode: true
    inheritance:
    - libsdisguises
